### PR TITLE
Support TSV output.

### LINKED ISSUE #25: Provide TSV export
4 columns:

 * subject
 * predicate
 * object
 * named graph (e.g redundant, non-redundant)

With CURIEs

Why:

 1. many tools speak TSV (pandas, sqlite, cut, grep)
 2. loading the ttl files using the OWLAPI causes inference that the OPs are actually APs. I believe querying by robot will route through the API causing injection of these unwanted triples
 3. having the two files combined into one is useful

### PR DESCRIPTION
**Pull request by balhoff**
Fixes #25.

### CODE REVIEW

**Comment by cmungall** [comment]
can this be merged?

**Comment by balhoff** [comment]
I have some work to make it mergeable. I did for version 1 and then did some major changes for version 2.

**Comment by cmungall** [comment]
it would be awesome to have this or a similar PR merged :-)

**Comment by balhoff** [comment]
Superseded by #162.

**Pull request closed without merging**
